name: Node.js CI

on:
  push:
    tags:
      - "v1.*"
      - "v2.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
      with:
        cache-dependency-path: src/package-lock.json
        submodules: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --prefix=src
    #- run: npm run build
    - uses: JS-DevTools/npm-publish@v3
      with:
        access: "public"
        token: ${{ secrets.NPM_TOKEN }}
        package: ./src/package.json